
stages:
  - pre_deploy
  - deploy_to_staging
  - tests_on_staging
  - deploy_to_prod

#workflow:
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "push"'
#      when: never
#    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_MERGE_REQUEST_APPROVED'
#      when: always

#  CI_MERGE_REQUEST_TARGET_BRANCH_NAME

variables:
  APP_DIR: /root/projects/automation_dashboard

code_quality:
  stage:
    pre_deploy
  image: python:3.11

  script:
#    - pip3 install -r ./requirements.txt
#    - pylint ./app --recursive=true -E
    - echo $CI_PIPELINE_SOURCE
    - echo $CI_COMMIT_BRANCH
    - echo $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "main"'
#      when: always
#      allow_failure: false
#    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_MERGE_REQUEST_APPROVED'
#      when: always
deploy_to_staging:
  stage:
    deploy_to_staging
  variables:
    ENVIRONMENT: staging

  script:
    - echo "job 1"
    - ls
    - chmod 400 ${DRP3_KEY}
    - ssh -o StrictHostKeyChecking=no -i ${DRP3_KEY} "root@198.199.111.109" "mkdir -p ${APP_DIR}/${ENVIRONMENT}/"
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./app root@198.199.111.109:${APP_DIR}/${ENVIRONMENT}/
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./requirements.txt root@198.199.111.109:${APP_DIR}/${ENVIRONMENT}/
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "python3 -m venv ${APP_DIR}/${ENVIRONMENT}/venv_dashboard"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "${APP_DIR}/${ENVIRONMENT}/venv_dashboard/bin/python -m pip install -r ${APP_DIR}/${ENVIRONMENT}/requirements.txt"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "cd ${APP_DIR}/${ENVIRONMENT}/app && ${APP_DIR}/${ENVIRONMENT}/venv_dashboard/bin/python -m gunicorn --workers 1 --bind 127.0.0.1:9099 app:app --daemon --reload"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_MERGE_REQUEST_APPROVED'
      when: always

deploy_to_prod:
  stage:
    deploy_to_prod
  script:
    - echo "job 1"
    - ls
    - ls
    - chmod 400 ${DRP3_KEY}
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./app root@198.199.111.109:/root/projects/automation_dashboard/
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./requirements.txt root@198.199.111.109:/root/projects/automation_dashboard/
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "python3 -m venv /root/projects/automation_dashboard/venv_dashboard"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "/root/projects/automation_dashboard/venv_dashboard/bin/python -m pip install -r /root/projects/automation_dashboard/requirements.txt"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "cd /root/projects/automation_dashboard/app && /root/projects/automation_dashboard/venv_dashboard/bin/python -m gunicorn --workers 1 --bind 127.0.0.1:9098 app:app --daemon --reload"

  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
      allow_failure: false

uat_automation_on_stage:
  stage:
    tests_on_staging
  image: python:3.11
  services:
    - selenium/standalone-firefox
  script:
    - echo "ABC"
    - pip3 install -r ./uat_automation/requirements.txt
    - pytest -m healthcheck ./uat_automation/tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_MERGE_REQUEST_APPROVED'
      when: always
  #my_job_2:
#  stage:
#    secondStage
#  script:
#    - echo "foo bar"