
stages:
  - deploy_to_staging
  - tests_on_staging
  - deploy_to_prod


#deploy_to_staging:
#  stage:
#    deploy_to_staging
#  script:
#    - echo "job 1"
#    - ls
#    - chmod 400 ${DRP3_KEY}
#    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./app root@198.199.111.109:/root/projects/automation_dashboard/
#    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./requirements.txt root@198.199.111.109:/root/projects/automation_dashboard/
#    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "python3 -m venv /root/projects/automation_dashboard/venv_dashboard"
#    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "/root/projects/automation_dashboard/venv_dashboard/bin/python -m pip install -r /root/projects/automation_dashboard/requirements.txt"
#    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "cd /root/projects/automation_dashboard/app && /root/projects/automation_dashboard/venv_dashboard/bin/python -m gunicorn --workers 1 --bind 127.0.0.1:9099 app:app --daemon --reload"
##    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "venv_dashboard/bin/python /root/projects/automation_dashboard/app/app.py"
##    - ssh -i $DRP3_KEY "root@198.199.111.109 "python3 /root/projects/automation_dashboard/app/app.py"
##    - scp -r ./app ${DASHBOARD_USER}@${DASHBOARD_HOST}:/

deploy_to_prod:
  stage:
    deploy_to_prod
  script:
    - echo "job 1"
    - ls
    - ls
    - chmod 400 ${DRP3_KEY}
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./app root@198.199.111.109:/root/projects/automation_dashboard/
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./requirements.txt root@198.199.111.109:/root/projects/automation_dashboard/
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "python3 -m venv /root/projects/automation_dashboard/venv_dashboard"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "/root/projects/automation_dashboard/venv_dashboard/bin/python -m pip install -r /root/projects/automation_dashboard/requirements.txt"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "cd /root/projects/automation_dashboard/app && /root/projects/automation_dashboard/venv_dashboard/bin/python -m gunicorn --workers 1 --bind 127.0.0.1:9098 app:app --daemon --reload"
  #    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "venv_dashboard/bin/python /root/projects/automation_dashboard/app/app.py"
  #    - ssh -i $DRP3_KEY "root@198.199.111.109 "python3 /root/projects/automation_dashboard/app/app.py"
  #    - scp -r ./app ${DASHBOARD_USER}@${DASHBOARD_HOST}:/
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
      allow_failure: false

uat_automation:
  stage:
    tests_on_staging
  image: python:3.11
  services:
    - selenium/standalone-firefox
  script:
    - echo "ABC"
    - pip3 install -r ./requirements.txt
    - pytest -m healthcheck

  #my_job_2:
#  stage:
#    secondStage
#  script:
#    - echo "foo bar"