
stages:
  - firstStage
  - secondStage


my_job_1:
  stage:
    firstStage
  script:
    - echo "job 1"
#    - ssh -i $DRP3_KEY
    - scp -i $DRP3_KEY -r ./app root@198.199.111.109:/root/projects/automation_dashboard/
#    - scp -r ./app ${DASHBOARD_USER}@${DASHBOARD_HOST}:/

my_job_2:
  stage:
    secondStage
  script:
    - echo "foo bar"