
stages:
  - pre_deploy
  - deploy_to_staging
  - tests_on_staging
  - deploy_to_prod

#workflow:
#  rules:
#    - if: '$CI_PIPELINE_SOURCE == "push"'
#      when: never
#    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_MERGE_REQUEST_APPROVED'
#      when: always

#  CI_MERGE_REQUEST_TARGET_BRANCH_NAME

variables:
  PY_IMAGE: python:3.11
  APP_DIR: /root/projects/automation_dashboard

code_quality:
  stage:
    pre_deploy
  image: $PY_IMAGE
  script:
    - pip3 install -r ./requirements.txt
    - pylint ./automationdashboard --recursive=true -E
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always


deploy_to_staging:
  stage:
    deploy_to_staging
  variables:
    ENVIRONMENT: staging
    APP_INSTANCE_DIR: ${APP_DIR}/${ENVIRONMENT}
    VIRTUAL_ENVIRONMENT: ${APP_INSTANCE_DIR}/venv_dashboard
  script:
    - echo "job 1"
    - ls
    - chmod 400 ${DRP3_KEY}
    - ssh -o StrictHostKeyChecking=no -i ${DRP3_KEY} "root@198.199.111.109" "mkdir -p ${APP_INSTANCE_DIR}"
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./automationdashboard root@198.199.111.109:${APP_INSTANCE_DIR}
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./requirements.txt root@198.199.111.109:${APP_INSTANCE_DIR}
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "python3 -m venv ${VIRTUAL_ENVIRONMENT}"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "${VIRTUAL_ENVIRONMENT}/bin/python -m pip install -r ${APP_INSTANCE_DIR}/requirements.txt"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "cd ${APP_INSTANCE_DIR}/automationdashboard && export PYTHONPATH=${APP_INSTANCE_DIR} && source variables.sh && ${VIRTUAL_ENVIRONMENT}/bin/python -m gunicorn --workers 1 --bind 127.0.0.1:9099 automationdashboard:app --daemon --reload"
#  rules:
#    - if: '$CI_COMMIT_BRANCH == "develop"'
#      when: always
#      allow_failure: false


deploy_to_prod:
  stage:
    deploy_to_prod
  script:
    - echo "job 1"
    - ls
    - ls
    - chmod 400 ${DRP3_KEY}
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./app root@198.199.111.109:/root/projects/automation_dashboard/
    - scp -o StrictHostKeyChecking=no -i ${DRP3_KEY} -r ./requirements.txt root@198.199.111.109:/root/projects/automation_dashboard/
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "python3 -m venv /root/projects/automation_dashboard/venv_dashboard"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "/root/projects/automation_dashboard/venv_dashboard/bin/python -m pip install -r /root/projects/automation_dashboard/requirements.txt"
    - ssh -o StrictHostKeyChecking=no -i $DRP3_KEY "root@198.199.111.109" "cd /root/projects/automation_dashboard/app && /root/projects/automation_dashboard/venv_dashboard/bin/python -m gunicorn --workers 1 --bind 127.0.0.1:9098 app:app --daemon --reload"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
      allow_failure: false

uat_automation_on_stage:
  stage:
    tests_on_staging
  image: $PY_IMAGE
  services:
    - selenium/standalone-firefox
  script:
    - echo "ABC"
    - pip3 install -r ./uat_automation/requirements.txt
    - pytest -m healthcheck ./uat_automation/tests
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: always
      allow_failure: false
